spring.application.name=sepedaweb

# Paksa Spring Boot hanya membaca dari variabel environment Railway
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/sepeda_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Gunakan Dialect yang lebih umum agar Hibernate tidak bingung
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect